[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  functionsPort = 9999